### ISSUE TITLE
Role in ecosystem

### ISSUE THREAD

**Issue by timholy** [yurivish/AssociativeArrays.jl#5]
I got here expecting this to be an alternative representation of a `SparseArray`, where the non-zero entries are stored in a `Dict(index => value)`. That doesn't appear to be what this is for, but the README basically expect me to go read an entire book to find out what they are for. It might be nice to say a few more words about the intent of the package.

It would also help to delete the REQUIRE file, as it causes problems for newer Julia versions.

**Comment by yurivish** [comment]
Hi Tim, I would be fine unregistering this package since I don’t plan to return to it. The idea of this particular representation is to represent tabular data in a sparse Boolean form where every unique value in a field gets its own column.

I’m not sure about the process of removing a package from the Julia registry but if you know how and have the power, feel free to do it – the package name might be useful for other folks.

**Comment by timholy** [comment]
Nope, I have no idea. I'm not even sure if it's possible. I'd suggest asking on discourse or slack.

**Comment by yurivish** [comment]
Ok. Might just change the readme then, if I think of a way to clarify that this was just an experiment.

**Comment by yurivish** [comment]
(Done)

**Comment by yurivish** [comment]
Added a link to https://d4m.mit.edu/publications, which describe the idea.
